#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start NTP daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/bin/ntpd
PIDFILE=/var/run/ntpd.pid

test -x $DAEMON || exit 5

case $1 in
	start)
		log_daemon_msg "Starting NTP server" "ntpd"
		$( (while [ 1 ]; do
			if [ $(ifconfig | grep "wlan0" -A 1 | grep "inet addr" | wc -l) -eq 1 ] || [ $(ifconfig | grep "eth0" -A 1 | grep "inet addr" | wc -l) -eq 1 ]; then
	  			start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p nl.pool.ntp.org
				break;
			fi
			sleep 1;
		done) &);
		#log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping NTP server" "ntpd"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "NTP server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
